# Generated by Django 3.2.6 on 2021-09-03 13:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('environment_education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'استاد',
                'ordering': ['id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UnivercityPersident',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'رییس دانشگاه',
                'ordering': ['id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UniversityStaff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=11)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_college', to='environment_education.college')),
            ],
            options={
                'verbose_name_plural': 'کارمند دانشگاه',
                'ordering': ['id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('date_of_entery', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='environment_education.college')),
                ('lessons', models.ManyToManyField(related_name='lessons', to='environment_education.Lesson')),
                ('rented_book', models.ManyToManyField(blank=True, null=True, related_name='rent', to='library.Rent')),
            ],
            options={
                'verbose_name_plural': 'دانشجو',
                'ordering': ['id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_num', models.IntegerField(blank=True, null=True)),
                ('date_exam', models.DateTimeField(blank=True, null=True)),
                ('code', models.IntegerField()),
                ('cluss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clUss', to='environment_education.class')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='environment_education.lesson')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='persons.professor')),
                ('students', models.ManyToManyField(related_name='students', to='persons.Student')),
            ],
            options={
                'verbose_name_plural': 'کلاس برگزاری درس',
                'ordering': ['id'],
            },
        ),
    ]
