# Generated by Django 3.2.6 on 2021-09-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rented_book',
            field=models.ManyToManyField(blank=True, null=True, related_name='rented_books', to='library.Rent'),
        ),
    ]
